"""Constants module of DebugGroup."""

INDIVIDUAL_GROUP_INDENTATION_TEXT = '| '
AFTER_GROUP_INDENTATION_TEXT      = '  '

INIT_PRINT_INDENTATION_TEXT       = '=> '
PARAGRAPH_INDENTATION_TEXT        = '   '

INTERNAL_GROUP_INDENTATION_TEXT   = '| '
